server:
  port: 8085
  servlet:
    context-path: /java_test

spring:
  application:
    name: java_test

  datasource:
    url: "jdbc:h2:mem:testdb;INIT=CREATE SCHEMA IF NOT EXISTS E_COMMERCE\\;SET SCHEMA E_COMMERCE"
    driverClassName: org.h2.Driver
    username: test
    password: test

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      data-locations: classpath:db/data.sql
      mode: always

  h2:
    console.enabled: true
    console.path: /h2-console
    console.settings.trace: false
    console.settings.web-allow-others: false

